# Generated by Django 5.2.1 on 2025-05-23 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_subdepartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gondola',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gondola',
            name='subdepartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.subdepartment'),
        ),
    ]
