# Generated by Django 5.2.1 on 2025-06-09 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_booking_booking_id_remove_gondola_gondola_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gondola',
            old_name='name',
            new_name='gondola_name',
        ),
        migrations.RenameField(
            model_name='gondolatype',
            old_name='name',
            new_name='gondola_type_name',
        ),
    ]
