# Generated by Django 5.2.1 on 2025-06-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_rename_name_gondola_gondola_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='gondola',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('PENDING', 'Pending'), ('RESERVED', 'Reserved')], default='available', max_length=20),
        ),
    ]
